sonar.projectKey=metricas_Grupo07_v2
sonar.projectName=metricas_Grupo07_v2
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.login=sqa_c2f31e081254cb39c2aac92a0004c8b910d4efec
sonar.host.url=http://localhost:9000
