sonar.projectKey=metricas_Grupo07_v2
sonar.projectName=metricas_Grupo07_v2
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.login=sqa_4ed8b5ac34f36347fa618afe86c84a73e53689d7
sonar.host.url=http://localhost:9000
