sonar.projectKey=metricas_Grupo07_v2
sonar.organization=grupo072026
sonar.projectName=metricas_Grupo07_v2
sonar.projectVersion=1.0

# Código fuente
sonar.sources=.

# Tests
sonar.tests=tests

# Excluir tests del source principal
sonar.exclusions=tests/**,**/node_modules/**,**/__pycache__/**,**/.venv/**

# Encoding
sonar.sourceEncoding=UTF-8
sonar.javascript.eslint.reportPaths=eslint-report.json

sonar.javascript.lcov.reportPaths=coverage/lcov.info
